version: "2.4"

services:
  elasticsearch:
    container_name: elastic_container
    build:
      context: /home/benaya/IdeaProjects/Rest_redo/src/main/java/com/example/rest_redo/config/elastic
    volumes:
      - type: bind
        source: ./src/main/java/com/example/rest_redo/config/elastic/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - elastic
    healthcheck:
      test: curl -u elastic:elastic -s -f elastic_container:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  employee:
    container_name: employee_container
    build:
      dockerfile: Dockerfile
      context: .
    depends_on: {"elasticsearch": {"condition": "service_healthy"}}
    ports:
      - "8080"
    networks:
      - elastic
volumes:
  elasticsearch:
    driver: local

networks:
  elastic:
    driver: bridge
